### ISSUE TITLE
Validation on Mac can't find VERSION-*

### ISSUE THREAD

**Issue by meeas** [joswr1ght/bitfit#10]
Meeas-MBP15:SEC642 justin$ pwd
/Volumes/SEC642
Meeas-MBP15:SEC642 justin$ bitfit.py -v .
Error: I can't find a VERSION-*.txt file in .. Make sure the file exists, has a filename extension of
".txt" and is readable, then try again.
Meeas-MBP15:SEC642 justin$ ls -l
total 6030168
drwxrwxrwx@ 1 justin  staff        4096 May 23 14:38 Optional Software
-rwxrwxrwx@ 1 justin  staff       91736 Aug  5 07:44 SEC642 Student Instructions.pdf
-rwxrwxrwx  1 justin  staff  3087342102 Jul 12 11:44 SamuraiWTF-3.4.vmwarevm.zip
-rwxrwxrwx  1 justin  staff        3407 Aug  5 08:31 VERSION-SEC642-16-1.txt
Meeas-MBP15:SEC642 justin$ python
Python 2.7.11 (default, Mar 10 2016, 09:47:20) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin

**Comment by joswr1ght** [comment]
I need some more information to troubleshoot this issue.  I'm unable to reproduce it on my OS X box:

```
Joshuas-MacBook-Pro:tmp jwright$ ~/Dev/bitfit/bitfit.py . > VERSION-SEC642-16-1.txt
Joshuas-MacBook-Pro:tmp jwright$ ~/Dev/bitfit/bitfit.py -v .
Validation complete, no errors.
```

Instead of specifying the relative path `.`, can you specify an absolute path and try again?  Maybe also add a `print verfile` after line 150 and send me that output?

**Comment by joswr1ght** [comment]
Cannot reproduce, no response from Justin. Closing issue, feel free to re-open if you can reproduce this error.
