### ISSUE TITLE
Auto-report validation tests to google docs

### ISSUE THREAD

**Issue by philhagen** [joswr1ght/bitfit#4]
Long-lead/big-dream item...
Would be fantastic to have bitfit (optionally?) report to the Google Sheet we use to track validation runs.  I can do this via GDocs API.

Assign to me - I'll start tracking feasibility for this.

**Comment by philhagen** [comment]
also need to track:
- bitfit version number
- transfer speed
- public (and private?) IP address(es) where run
- username running it?
- host OS
- VERSION filename used for validation
- upon validation failure, the filename(s) that failed validation
- if bitfit itself fails, maybe some information about where in the code it happened?
- can we get vendor and product IDs from the USB?

**Comment by joswr1ght** [comment]
I don't want this functionality.  Bitfit was designed to be simple and this increases complexity significantly.  It's not Bitfit's job to auto-report validation tests online.  I'm OK with adding more information to comments in the VERSION file for parsing, or adding more STDOUT information with the test mode, but not auto-submitting to any online resource.

**Comment by philhagen** [comment]
understand.  had only thought of the possibilities to use the tool in a broader capacity.  We tested 180 USBs recently, and it was a lot of copy-pasting into a web form.  Maybe something to consider for an independent fork down the road, and was not something envisioned as a default behavior.

**Comment by philhagen** [comment]
Thought more about this on rest of plane and drive.  Agree it doesn't fit in the core bitfit functionality, but can still see potential value.  May be better aligned with a wrapper tool that calls bitfit itself?

**Comment by joswr1ght** [comment]
Sure - we can add any content to the comment section in the beginning of the bitfit output.  Something like:

```
bitfit .
# bitfit 1.1.0 output generated on 2015-11-10 12:05:38.425487 by jwright
# ./bitfit.py .
# CSV,data,here,ignored,elsewhere
# filename,MD5,SHA1
.git/COMMIT_EDITMSG,042cd7541adb5167176518e3d3f49e02,a2246fa05548757871daa0d610b945fc32f544c0
.git/FETCH_HEAD,c61085acb3c71bb58e90c4358819c68d,375d73571a971c9435d57b071c4ec46271b83cdf
bitfit . | tee VERSION-SEC575-2015.XXX.txt | ./phils-tool-that-posts-to-googledocs.py
```

That seems like a very Unix'y way to do it.

-Josh
